version: '3.1'

services:
  mariadb:
    build:
      context: ./mariadb/
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - ./mounts/database/:/var/lib/mysql
    env_file:
      - .env
    networks:
      - internal
  php-fpm:
    build:
      context: ./php-fpm/
      dockerfile: Dockerfile
      args:
        DATABASE_URL: mysql://${MARIADB_USER}:${MARIADB_PASSWORD}@${MARIADBHOST}:3306/${MARIADB_DATABASE}
    volumes:
      - ./mounts/data:/var/www/data
    env_file:
      - .env
    networks:
      - internal
    depends_on:
      - mariadb
  sandbox:
    build:
      context: ./sandbox/
      dockerfile: Dockerfile
    volumes:
      - ./mounts/data:/data
    env_file:
      - .env
    networks:
      - internal
    depends_on:
      - mariadb
      - php-fpm
  nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - internal
    depends_on:
      - php-fpm
networks:
  internal:
    driver: bridge
