version: '3.1'

services:
  mariadb:
    build:
      context: ./files/mariadb/
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - ./mounts/database/:/var/lib/mysql
    env_file:
      - .env
    networks:
      - internal
  php-fpm:
    build:
      dockerfile: ./files/php-fpm/Dockerfile
    volumes:
      - ./mounts/data:/var/www/data
    env_file:
      - .env
    networks:
      - internal
    depends_on:
      - mariadb
  judge:
    build:
      dockerfile: ./files/judge/Dockerfile
    volumes:
      - ./mounts/data:/data
    env_file:
      - .env
    networks:
      - internal
    depends_on:
      - mariadb
      - php-fpm
  nginx:
    build:
      context: ./files/nginx/
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - internal
    depends_on:
      - php-fpm
networks:
  internal:
    driver: bridge
